image:
  file: .gitpod.Dockerfile

tasks:
  - name: "Use SDK 20"
    init: sdk install java 20.0.1-tem && sdk default java 20.0.1-tem

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview
