name: Android

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: mvn package
        run: cd halban-parent && mvn --batch-mode --update-snapshots install

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install linux libraries
        run: |
          sudo apt-get update
          sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev

      - name: mvn gluonfx:build
        run: cd halban-parent && mvn --batch-mode --update-snapshots gluonfx:build gluonfx:package -f sokoban-app -P android

      - name: Copy packages to staging
        run: |
          mkdir staging
          cp -r target/gluonfx/aarch64-android/gvm/halban.* staging

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging

#      - name: Upload
#        uses: actions/upload-artifact@v2
#        with:
#          name: Package
#          path: staging
