name: Macos

on:
  push:
    branches: [ macos ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: mvn package
        run: cd halban-parent && mvn --batch-mode --update-snapshots install

      - name: mvn jpackage
        run: cd halban-parent && mvn --batch-mode --update-snapshots jpackage:jpackage -f sokoban-app -P macos

      - name: Show files
        run: ls -l halban-parent/sokoban-app/target/jpackage

      - name: Copy packages to staging
        run: |
          mkdir staging
          cp halban-parent/sokoban-app/target/jpackage/halban-*.dmg staging

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: dmg
          path: staging
