name: Macos

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: mvn package
        run: cd halban-parent && mvn --batch-mode --update-snapshots install

      - name: mvn package
        run: cd halban-parent && mvn --batch-mode --update-snapshots jpackage:jpackage -f sokoban-app

      - name: Make staging directory
        run: mkdir staging

      - name: Copy packages to staging
        run: ls target/*/*

#      - name: Upload
#        uses: actions/upload-artifact@v2
#        with:
#          name: Package
#          path: staging
